services:
  - type: web
    name: github-ai-reviewer
    env: node
    plan: starter  # or 'free' for free tier
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /health
    autoDeploy: true